version: "3.2"
networks:
  default:
    driver: bridge
volumes:
  tracker_db_data:
  mq_data:
  reporter_db_data:
  reporter_db_config_data:
services:
  tracker:
    build:
      context: ./tracker
      dockerfile: Dockerfile
      args:
        TRACKER_JAR: build/libs/tracker.jar
    ports:
      - 8080:8080
    depends_on:
      - tracker_db
      - mq
    entrypoint: /wait-for tracker_db:5432 mq:5672 -t 30 -- java -jar tracker.jar
  tracker_db:
    image: postgres:10.2-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tracker
    ports:
      - 5433:5432
    volumes:
      - tracker_db_data:/var/lib/postgresql/data
  reporter:
    build:
      context: ./reporter
      dockerfile: Dockerfile
      args:
        REPORTER_JAR: build/libs/reporter.jar
    ports:
      - 8081:8080
    depends_on:
      - mq
    entrypoint: /wait-for mq:5672 -t 30 -- java -jar reporter.jar
  reporter_db:
    image: mongo:3.7-jessie
    ports:
      - 27018:27017
    volumes:
      - reporter_db_data:/data/db
      - reporter_db_config_data:/data/configdb
  mq:
    image: rabbitmq:3.7.3-alpine
    ports:
      - 5673:5672
    volumes:
      - mq_data:/var/lib/rabbitmq