version: "3.2"
volumes:
  expenses-db-data:
  expenses-mq-data:
services:
  tracker:
    build:
      context: ./tracker
      dockerfile: Dockerfile
      args:
        TRACKER_JAR: build/libs/tracker.jar
    ports:
      - 8080:8080
    depends_on:
      - db
      - mq
    entrypoint: /wait-for tracker_db:5432 mq:5672 -t 30 -- java -jar tracker.jar
  reporter:
    build:
      context: ./reporter
      dockerfile: Dockerfile
      args:
        REPORTER_JAR: build/libs/reporter.jar
    ports:
      - 8081:8080
    depends_on:
      - db
      - mq
    entrypoint: /wait-for mq:5672 -t 30 -- java -jar reporter.jar
  db:
    image: postgres:10.5-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
    ports:
      - 5433:5432
    volumes:
      - expenses-db-data:/var/lib/postgresql/data
  mq:
    image: rabbitmq:3.7.8-alpine
    ports:
      - 5673:5672
    volumes:
      - expenses-mq-data:/var/lib/rabbitmq